services:
  loft-finder:
    image: ghcr.io/ammiratafabiano/loft-finder:latest
    container_name: loft-finder
    restart: unless-stopped
    volumes:
      - ./loft-finder/config.json:/app/config.json
      - ./loft-finder/storage.p:/app/storage.p
      - ./loft-finder/report.p:/app/report.p
      - ./loft-finder/conversationbot:/app/conversationbot
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
