services:
  loft-finder:
    image: ghcr.io/ammiratafabiano/loft-finder:latest
    container_name: loft-finder
    restart: unless-stopped
    volumes:
      - ./loft-finder/config.json:/app/config.json
      - ./loft-finder/data:/app/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
